# Generated by Django 5.0.1 on 2024-02-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=300)),
                ("expired_time", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("username", models.CharField(max_length=200, unique=True)),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=40, unique=True)),
                ("image", models.CharField(max_length=350, unique=True)),
                ("password", models.CharField(max_length=200)),
                ("bio", models.CharField(max_length=200)),
                ("phone_private", models.BooleanField()),
                ("image_private", models.BooleanField()),
                ("bio_private", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                (
                    "people",
                    models.ManyToManyField(related_name="Contacts", to="user.user"),
                ),
            ],
        ),
    ]
