# Generated by Django 5.0.1 on 2024-02-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_id", models.CharField(max_length=200)),
                ("user_id", models.CharField(max_length=200)),
                ("people", models.CharField(max_length=200)),
            ],
        ),
    ]
